before_install:
  - chmod +x mvnw
language: java
jdk:
  - oraclejdk8
services:
  - mysql
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_script:
- mysql -u root -e 'CREATE DATABASE talks;'
- mysql -u root -e "CREATE USER 'springuser'@'localhost' IDENTIFIED BY 'springuser';"
- mysql -u root -e "GRANT ALL ON talks.* TO 'springuser'@'localhost';"

script: mvn clean verify
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false